name: Build and Release Add-in

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.2.3

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish Add-in
        run: |
          $version = "${{ github.ref_name }}"
          dotnet build src/Atlas.Dna/Atlas.Dna.csproj -c Release -p:Version=$version -p:InformationalVersion=$version

      - name: Rename and zip release files
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}"
          $xll = "src/Atlas.Dna/bin/Release/net6.0-windows/publish/Atlas.Dna-AddIn64-packed.xll"
          $exe = "src/Atlas.Dna/bin/Release/net6.0-windows/AtlasAddInInstaller.exe"
          mkdir dist
          Copy-Item $exe "dist/AtlasAddInInstaller-$version.exe"
          Compress-Archive -Path dist/* -DestinationPath "AtlasAddIn-$version.zip"

      - name: Upload zipped release package
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: AtlasAddIn-*.zip

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download release zip
        uses: actions/download-artifact@v4
        with:
          name: release-zip
          path: .  # Save it to the current working directory

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AtlasAddIn-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
