name: Build and Release Add-in

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.2.3

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Set up certificate 
        run: | 
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12 
        shell: bash 
    
      - name: Set variables 
        id: variables 
        run: | 
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT 
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV" 
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV" 
          echo "SM_KEYPAIR_ALIAS=${{ secrets.SM_KEYPAIR_ALIAS }}" >> "$GITHUB_ENV" 
          echo "SM_CODE_SIGNING_CERT_SHA1_HASH=${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV" 
        shell: bash
    
      - name: Code signing with Software Trust Manager
        uses: digicert/ssm-code-signing@v1.0.0
    
      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish Add-in
        run: |
          $tag = "${{ github.ref_name }}"         # e.g., "v0.2.6"
          $version = $tag.TrimStart("v")          # e.g., "0.2.6"
          dotnet build src/Atlas.Dna/Atlas.Dna.csproj -c Release `
            -p:Version=$version `
            -p:InformationalVersion=$tag `
            -p:IncludeSourceRevisionInInformationalVersion=false
              
      - name: Rename and zip release files
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}"
          $xll = "src/Atlas.Dna/bin/Release/net6.0-windows/publish/Atlas.Dna-AddIn64-packed.xll"
          $exe = "src/Atlas.Dna/bin/Release/net6.0-windows/AtlasAddInInstaller-$version.exe"
          mkdir dist
          Copy-Item $exe "dist/AtlasAddInInstaller-$version.exe"
          Compress-Archive -Path dist/* -DestinationPath "AtlasAddIn-$version.zip"

      - name: Upload zipped release package
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: AtlasAddIn-*.zip

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download release zip
        uses: actions/download-artifact@v4
        with:
          name: release-zip
          path: .  # Save it to the current working directory

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AtlasAddIn-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
